
spring:
  devtools:
    restart:
     enable=true

  application:
    name: gatewaya
  cloud:
    gateway:
      routes:
        #将 micro-service-cloud-provider-dept-8001 提供的服务隐藏起来，不暴露给客户端，只给客户端暴露 API 网关的地址 9527
        - id: provider_user_routh   #路由 id,没有固定规则，但唯一，建议与服务名对应
          uri: lb://userservice          #匹配后提供服务的路由地址
          predicates:
            #以下是断言条件，必选全部符合条件
            - Path=/user/**               #断言，路径匹配 注意：Path 中 P 为大写
            - Method=GET #只能时 GET 请求时，才能访问
#        - id: provider_user_routh   #路由 id,没有固定规则，但唯一，建议与服务名对应
#          uri: http://localhost:8080
#          predicates:
#            - Path=/order/**
#            - Method=GET
#    nacos:
#      server-addr: localhost:8848


#
#  pool:
#    coreSize:5
#    maxSize=10
#    queue-capacity=5
#    keep-alive=60
#    thread-name-prefix=dw-task-
# 核心线程池数

# 最大线程池数

# 任务队列的容量

# 非核心线程的存活时间

# 线程池的前缀名称
server:
  port: 9527
eureka:
  client:
    # 服务注册中心也会将自己作为客户端来尝试注册自己,为true（默认）时自动生效
    register-with-eureka: true
    # 检索服务选项，当设置为True(默认值)时，会进行服务检索,注册中心不负责检索服务。
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/

  instance:
    hostname: eureka-server
  server:
    enable-self-preservation: false