spring:
  datasource:
    url: jdbc:mysql://localhost:3306/homeservice?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: daiwei
  #线程池配置
  pool:
    coreSize: 5
    maxSize: 10
    queueSize: 5
    keepAlive: 60
    prefixName: dw-task-
  task: on

  application:
    name: homeservice

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9527/eureka/
mybatis-plus:
  type-aliases-package: com.dw.entity
  mapper-locations: classpath:/mybatis/mapper/*.xml

server:
  port: 8083

logging:
  pattern:
    console: "[%X{log_id}] [%X{traceid}] [%d{yyyy-MM-dd HH:mm:ss}] [%p] [%C{1}:%L] %m%n"
    file: "[%X{log_id}] [%X{traceid}] [%d{yyyy-MM-dd HH:mm:ss}] [%p] [%C{1}:%L] %m%n"
  level:
    com.springboot.cloud.gateway: info
    com.jalja.org.spring: info
  config: classpath:logback.xml
  path: logs/
  file:
    max-size: 1GB
feign:
  hystrix:
    enabled: true