spring:
  datasource:
    url: jdbc:mysql://rm-wd6hdei95p1qnw45vuo.mysql.cn-chengdu.rds.aliyuncs.com:3306/hioc?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: testhioc
    password: testHioc226
    driver-class-name: com.mysql.jdbc.Driver

  pool:
    coreSize: 5
    maxSize: 10
    queueSize: 5
    keepAlive: 60
    prefixName: dw-task-
  task: on

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/



server:
  port: 8082

logging:
  level:
    com.dw.dao: debug
