spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userservice?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: daiwei
  pool:
    coreSize: 5
    maxSize: 10
    queueSize: 5
    keepAlive: 60
    prefixName: dw-task-
  task: on
mybatis-plus:
  config-location: classpath:/mybatis/mybatis-config.xml
  type-aliases-package: com.dw.domain
  mapper-locations: classpath:/mybatis/mapper/*.xml

server:
  port: 8081

logging:
  level:
    com.dw.dao: debug