spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderservice?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: daiwei
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: localhost:8848